gphelp_link('var', "#var%2F1").
gphelp_link('nonvar', "#var%2F1").
gphelp_link('atom', "#var%2F1").
gphelp_link('integer', "#var%2F1").
gphelp_link('float', "#var%2F1").
gphelp_link('number', "#var%2F1").
gphelp_link('atomic', "#var%2F1").
gphelp_link('compound', "#var%2F1").
gphelp_link('callable', "#var%2F1").
gphelp_link('ground', "#var%2F1").
gphelp_link('is_list', "#var%2F1").
gphelp_link('list', "#var%2F1").
gphelp_link('partial_list', "#var%2F1").
gphelp_link('list_or_partial_list', "#var%2F1").
gphelp_link('(=)', "#sec74").
gphelp_link('unify_with_occurs_check', "#sec75").
gphelp_link('(\\=)', "#sec76").
gphelp_link('(==)', "#%28%3D%3D%29%2F2").
gphelp_link('(\\==)', "#%28%3D%3D%29%2F2").
gphelp_link('(@<)', "#%28%3D%3D%29%2F2").
gphelp_link('(@=<)', "#%28%3D%3D%29%2F2").
gphelp_link('(@>)', "#%28%3D%3D%29%2F2").
gphelp_link('(@>=)', "#%28%3D%3D%29%2F2").
gphelp_link('compare', "#compare%2F3").
gphelp_link('functor', "#functor%2F3").
gphelp_link('arg', "#arg%2F3").
gphelp_link('(=..)', "#%28%3D..%29%2F2").
gphelp_link('copy_term', "#sec85").
gphelp_link('term_variables', "#sec86").
gphelp_link('term_variables', "#sec86").
gphelp_link('subsumes_term', "#sec87").
gphelp_link('acyclic_term', "#sec88").
gphelp_link('term_hash', "#term-hash%2F4").
gphelp_link('term_hash', "#term-hash%2F4").
gphelp_link('setarg', "#sec90").
gphelp_link('setarg', "#sec90").
gphelp_link('name_singleton_vars', "#name-singleton-vars%2F1").
gphelp_link('name_query_vars', "#name-query-vars%2F2").
gphelp_link('bind_variables', "#bind-variables%2F2").
gphelp_link('numbervars', "#bind-variables%2F2").
gphelp_link('numbervars', "#bind-variables%2F2").
gphelp_link('term_ref', "#sec95").
gphelp_link('(is)', "#sec98").
gphelp_link('(=:=)', "#%28%3D%3A%3D%29%2F2").
gphelp_link('(=\\=)', "#%28%3D%3A%3D%29%2F2").
gphelp_link('(<)', "#%28%3D%3A%3D%29%2F2").
gphelp_link('(=<)', "#%28%3D%3A%3D%29%2F2").
gphelp_link('(>)', "#%28%3D%3A%3D%29%2F2").
gphelp_link('(>=)', "#%28%3D%3A%3D%29%2F2").
gphelp_link('succ', "#sec100").
gphelp_link('asserta', "#sec103").
gphelp_link('assertz', "#sec103").
gphelp_link('retract', "#sec104").
gphelp_link('retractall', "#sec105").
gphelp_link('clause', "#sec106").
gphelp_link('abolish', "#abolish%2F1").
gphelp_link('current_predicate', "#current-predicate%2F1").
gphelp_link('predicate_property', "#predicate-property%2F2").
gphelp_link('findall', "#sec113").
gphelp_link('bagof', "#sec114").
gphelp_link('setof', "#sec114").
gphelp_link('current_input', "#sec117").
gphelp_link('current_output', "#sec118").
gphelp_link('set_input', "#set-input%2F1").
gphelp_link('set_output', "#set-output%2F1").
gphelp_link('open', "#open%2F4").
gphelp_link('open', "#open%2F4").
gphelp_link('close', "#close%2F2").
gphelp_link('close', "#close%2F2").
gphelp_link('flush_output', "#flush-output%2F1").
gphelp_link('flush_output', "#flush-output%2F1").
gphelp_link('current_stream', "#current-stream%2F1").
gphelp_link('stream_property', "#stream-property%2F2").
gphelp_link('at_end_of_stream', "#sec126").
gphelp_link('at_end_of_stream', "#sec126").
gphelp_link('stream_position', "#stream-position%2F2").
gphelp_link('set_stream_position', "#set-stream-position%2F2").
gphelp_link('seek', "#sec129").
gphelp_link('character_count', "#sec130").
gphelp_link('line_count', "#line-count%2F2").
gphelp_link('line_position', "#line-position%2F2").
gphelp_link('stream_line_column', "#sec133").
gphelp_link('set_stream_line_column', "#sec134").
gphelp_link('add_stream_alias', "#add-stream-alias%2F2").
gphelp_link('current_alias', "#sec136").
gphelp_link('add_stream_mirror', "#add-stream-mirror%2F2").
gphelp_link('remove_stream_mirror', "#remove-stream-mirror%2F2").
gphelp_link('current_mirror', "#sec139").
gphelp_link('set_stream_type', "#set-stream-type%2F2").
gphelp_link('set_stream_eof_action', "#sec141").
gphelp_link('set_stream_buffering', "#set-stream-buffering%2F2").
gphelp_link('open_input_atom_stream', "#sec145").
gphelp_link('open_input_chars_stream', "#sec145").
gphelp_link('open_input_codes_stream', "#sec145").
gphelp_link('close_input_atom_stream', "#sec146").
gphelp_link('close_input_chars_stream', "#sec146").
gphelp_link('close_input_codes_stream', "#sec146").
gphelp_link('open_output_atom_stream', "#open-output-atom-stream%2F1").
gphelp_link('open_output_chars_stream', "#open-output-atom-stream%2F1").
gphelp_link('open_output_codes_stream', "#open-output-atom-stream%2F1").
gphelp_link('close_output_atom_stream', "#close-output-atom-stream%2F2").
gphelp_link('close_output_chars_stream', "#close-output-atom-stream%2F2").
gphelp_link('close_output_codes_stream', "#close-output-atom-stream%2F2").
gphelp_link('get_char', "#get-char%2F2").
gphelp_link('get_char', "#get-char%2F2").
gphelp_link('get_code', "#get-char%2F2").
gphelp_link('get_code', "#get-char%2F2").
gphelp_link('get_key', "#sec151").
gphelp_link('get_key', "#sec151").
gphelp_link('get_key_no_echo', "#sec151").
gphelp_link('get_key_no_echo', "#sec151").
gphelp_link('peek_char', "#sec152").
gphelp_link('peek_char', "#sec152").
gphelp_link('peek_code', "#sec152").
gphelp_link('peek_code', "#sec152").
gphelp_link('unget_char', "#sec153").
gphelp_link('unget_char', "#sec153").
gphelp_link('unget_code', "#sec153").
gphelp_link('unget_code', "#sec153").
gphelp_link('put_char', "#put-char%2F2").
gphelp_link('put_char', "#put-char%2F2").
gphelp_link('put_code', "#put-char%2F2").
gphelp_link('put_code', "#put-char%2F2").
gphelp_link('nl', "#put-char%2F2").
gphelp_link('nl', "#put-char%2F2").
gphelp_link('get_byte', "#sec156").
gphelp_link('get_byte', "#sec156").
gphelp_link('peek_byte', "#sec157").
gphelp_link('peek_byte', "#sec157").
gphelp_link('unget_byte', "#sec158").
gphelp_link('unget_byte', "#sec158").
gphelp_link('put_byte', "#sec159").
gphelp_link('put_byte', "#sec159").
gphelp_link('read_term', "#read-term%2F3").
gphelp_link('read_term', "#read-term%2F3").
gphelp_link('read', "#read-term%2F3").
gphelp_link('read', "#read-term%2F3").
gphelp_link('read_atom', "#read-atom%2F2").
gphelp_link('read_atom', "#read-atom%2F2").
gphelp_link('read_integer', "#read-atom%2F2").
gphelp_link('read_integer', "#read-atom%2F2").
gphelp_link('read_number', "#read-atom%2F2").
gphelp_link('read_number', "#read-atom%2F2").
gphelp_link('read_token', "#read-token%2F2").
gphelp_link('read_token', "#read-token%2F2").
gphelp_link('syntax_error_info', "#syntax-error-info%2F4").
gphelp_link('last_read_start_line_column', "#sec165").
gphelp_link('write_term', "#write-term%2F3").
gphelp_link('write_term', "#write-term%2F3").
gphelp_link('write', "#write-term%2F3").
gphelp_link('write', "#write-term%2F3").
gphelp_link('writeq', "#write-term%2F3").
gphelp_link('writeq', "#write-term%2F3").
gphelp_link('write_canonical', "#write-term%2F3").
gphelp_link('write_canonical', "#write-term%2F3").
gphelp_link('display', "#write-term%2F3").
gphelp_link('display', "#write-term%2F3").
gphelp_link('print', "#write-term%2F3").
gphelp_link('print', "#write-term%2F3").
gphelp_link('format', "#format%2F3").
gphelp_link('format', "#format%2F3").
gphelp_link('portray_clause', "#portray-clause%2F2").
gphelp_link('portray_clause', "#portray-clause%2F2").
gphelp_link('get_print_stream', "#sec169").
gphelp_link('op', "#op%2F3%3A%28Term-input%2Foutput%29").
gphelp_link('current_op', "#sec171").
gphelp_link('char_conversion', "#char-conversion%2F2").
gphelp_link('current_char_conversion', "#current-char-conversion%2F2").
gphelp_link('read_term_from_atom', "#read-term-from-atom%2F3").
gphelp_link('read_from_atom', "#read-term-from-atom%2F3").
gphelp_link('read_token_from_atom', "#read-term-from-atom%2F3").
gphelp_link('read_term_from_chars', "#sec176").
gphelp_link('read_from_chars', "#sec176").
gphelp_link('read_token_from_chars', "#sec176").
gphelp_link('read_term_from_codes', "#sec177").
gphelp_link('read_from_codes', "#sec177").
gphelp_link('read_token_from_codes', "#sec177").
gphelp_link('write_term_to_atom', "#sec178").
gphelp_link('write_to_atom', "#sec178").
gphelp_link('writeq_to_atom', "#sec178").
gphelp_link('write_canonical_to_atom', "#sec178").
gphelp_link('display_to_atom', "#sec178").
gphelp_link('print_to_atom', "#sec178").
gphelp_link('format_to_atom', "#sec178").
gphelp_link('write_term_to_chars', "#sec179").
gphelp_link('write_to_chars', "#sec179").
gphelp_link('writeq_to_chars', "#sec179").
gphelp_link('write_canonical_to_chars', "#sec179").
gphelp_link('display_to_chars', "#sec179").
gphelp_link('print_to_chars', "#sec179").
gphelp_link('format_to_chars', "#sec179").
gphelp_link('write_term_to_codes', "#sec180").
gphelp_link('write_to_codes', "#sec180").
gphelp_link('writeq_to_codes', "#sec180").
gphelp_link('write_canonical_to_codes', "#sec180").
gphelp_link('display_to_codes', "#sec180").
gphelp_link('print_to_codes', "#sec180").
gphelp_link('format_to_codes', "#sec180").
gphelp_link('see', "#sec183").
gphelp_link('tell', "#sec183").
gphelp_link('append', "#sec183").
gphelp_link('seeing', "#sec184").
gphelp_link('telling', "#sec184").
gphelp_link('seen', "#sec185").
gphelp_link('told', "#sec185").
gphelp_link('get0', "#sec186").
gphelp_link('get', "#sec186").
gphelp_link('skip', "#sec186").
gphelp_link('put', "#sec187").
gphelp_link('tab', "#sec187").
gphelp_link('expand_term', "#expand-term%2F2").
gphelp_link('term_expansion', "#expand-term%2F2").
gphelp_link('phrase', "#sec191").
gphelp_link('phrase', "#sec191").
gphelp_link('abort', "#abort%2F0").
gphelp_link('stop', "#abort%2F0").
gphelp_link('top_level', "#abort%2F0").
gphelp_link('break', "#abort%2F0").
gphelp_link('halt', "#abort%2F0").
gphelp_link('halt', "#abort%2F0").
gphelp_link('false', "#sec194").
gphelp_link('once', "#sec194").
gphelp_link('(\\+)', "#sec194").
gphelp_link('call', "#sec194").
gphelp_link('call_with_args', "#sec194").
gphelp_link('call_det', "#sec194").
gphelp_link('forall', "#sec194").
gphelp_link('repeat', "#sec195").
gphelp_link('between', "#sec196").
gphelp_link('for', "#sec196").
gphelp_link('atom_length', "#sec198").
gphelp_link('atom_concat', "#sec199").
gphelp_link('sub_atom', "#sec200").
gphelp_link('char_code', "#char-code%2F2").
gphelp_link('lower_upper', "#sec202").
gphelp_link('atom_chars', "#atom-chars%2F2").
gphelp_link('atom_codes', "#atom-chars%2F2").
gphelp_link('number_atom', "#number-atom%2F2").
gphelp_link('number_chars', "#number-atom%2F2").
gphelp_link('number_codes', "#number-atom%2F2").
gphelp_link('name', "#sec205").
gphelp_link('new_atom', "#sec206").
gphelp_link('new_atom', "#sec206").
gphelp_link('current_atom', "#current-atom%2F2").
gphelp_link('atom_property', "#atom-property%2F2").
gphelp_link('append', "#sec210").
gphelp_link('member', "#member%2F2").
gphelp_link('memberchk', "#member%2F2").
gphelp_link('reverse', "#sec212").
gphelp_link('delete', "#sec213").
gphelp_link('select', "#sec213").
gphelp_link('subtract', "#sec214").
gphelp_link('permutation', "#sec215").
gphelp_link('prefix', "#sec216").
gphelp_link('suffix', "#sec216").
gphelp_link('sublist', "#sec217").
gphelp_link('last', "#sec218").
gphelp_link('length', "#sec219").
gphelp_link('nth', "#sec220").
gphelp_link('max_list', "#sec221").
gphelp_link('min_list', "#sec221").
gphelp_link('sum_list', "#sec221").
gphelp_link('maplist', "#sec222").
gphelp_link('sort', "#sort%2F2").
gphelp_link('msort', "#sort%2F2").
gphelp_link('keysort', "#sort%2F2").
gphelp_link('sort', "#sort%2F2").
gphelp_link('msort', "#sort%2F2").
gphelp_link('keysort', "#sort%2F2").
gphelp_link('g_assign', "#g-assign%2F2").
gphelp_link('g_assignb', "#g-assign%2F2").
gphelp_link('g_link', "#g-assign%2F2").
gphelp_link('g_read', "#sec227").
gphelp_link('g_array_size', "#sec228").
gphelp_link('g_inc', "#sec229").
gphelp_link('g_inc', "#sec229").
gphelp_link('g_inco', "#sec229").
gphelp_link('g_inc', "#sec229").
gphelp_link('g_dec', "#sec229").
gphelp_link('g_dec', "#sec229").
gphelp_link('g_deco', "#sec229").
gphelp_link('g_dec', "#sec229").
gphelp_link('g_set_bit', "#sec230").
gphelp_link('g_reset_bit', "#sec230").
gphelp_link('g_test_set_bit', "#sec230").
gphelp_link('g_test_reset_bit', "#sec230").
gphelp_link('set_prolog_flag', "#set-prolog-flag%2F2").
gphelp_link('current_prolog_flag', "#current-prolog-flag%2F2").
gphelp_link('set_bip_name', "#set-bip-name%2F2").
gphelp_link('current_bip_name', "#current-bip-name%2F2").
gphelp_link('write_pl_state_file', "#write-pl-state-file%2F1").
gphelp_link('read_pl_state_file', "#write-pl-state-file%2F1").
gphelp_link('consult', "#consult%2F1").
gphelp_link('load', "#load%2F1").
gphelp_link('listing', "#listing%2F1").
gphelp_link('listing', "#listing%2F1").
gphelp_link('statistics', "#statistics%2F2").
gphelp_link('statistics', "#statistics%2F2").
gphelp_link('user_time', "#user-time%2F1").
gphelp_link('system_time', "#user-time%2F1").
gphelp_link('cpu_time', "#user-time%2F1").
gphelp_link('real_time', "#user-time%2F1").
gphelp_link('set_seed', "#sec246").
gphelp_link('randomize', "#sec246").
gphelp_link('get_seed', "#sec247").
gphelp_link('random', "#sec248").
gphelp_link('random', "#sec249").
gphelp_link('absolute_file_name', "#absolute-file-name%2F2").
gphelp_link('is_absolute_file_name', "#sec252").
gphelp_link('is_relative_file_name', "#sec252").
gphelp_link('decompose_file_name', "#sec253").
gphelp_link('prolog_file_name', "#prolog-file-name%2F2").
gphelp_link('argument_counter', "#argument-counter%2F1").
gphelp_link('argument_value', "#argument-value%2F2").
gphelp_link('argument_list', "#argument-list%2F1").
gphelp_link('environ', "#sec259").
gphelp_link('make_directory', "#sec260").
gphelp_link('delete_directory', "#sec260").
gphelp_link('change_directory', "#sec260").
gphelp_link('working_directory', "#sec261").
gphelp_link('directory_files', "#sec262").
gphelp_link('rename_file', "#sec263").
gphelp_link('delete_file', "#sec264").
gphelp_link('unlink', "#sec264").
gphelp_link('file_permission', "#file-permission%2F2").
gphelp_link('file_exists', "#file-permission%2F2").
gphelp_link('file_property', "#file-property%2F2").
gphelp_link('temporary_name', "#sec267").
gphelp_link('temporary_file', "#sec268").
gphelp_link('date_time', "#date-time%2F1").
gphelp_link('host_name', "#sec270").
gphelp_link('os_version', "#sec271").
gphelp_link('architecture', "#sec272").
gphelp_link('shell', "#sec273").
gphelp_link('shell', "#sec273").
gphelp_link('shell', "#sec273").
gphelp_link('system', "#sec274").
gphelp_link('system', "#sec274").
gphelp_link('spawn', "#sec275").
gphelp_link('spawn', "#sec275").
gphelp_link('popen', "#popen%2F3").
gphelp_link('exec', "#sec277").
gphelp_link('exec', "#sec277").
gphelp_link('fork_prolog', "#sec278").
gphelp_link('create_pipe', "#sec279").
gphelp_link('wait', "#wait%2F2").
gphelp_link('prolog_pid', "#sec281").
gphelp_link('send_signal', "#sec282").
gphelp_link('sleep', "#sec283").
gphelp_link('select', "#select%2F5").
gphelp_link('socket', "#sec287").
gphelp_link('socket_close', "#sec288").
gphelp_link('socket_bind', "#sec289").
gphelp_link('socket_connect', "#socket-connect%2F4").
gphelp_link('socket_listen', "#sec291").
gphelp_link('socket_accept', "#sec292").
gphelp_link('socket_accept', "#sec292").
gphelp_link('hostname_address', "#sec293").
gphelp_link('get_linedit_prompt', "#sec295").
gphelp_link('set_linedit_prompt', "#sec296").
gphelp_link('add_linedit_completion', "#sec297").
gphelp_link('find_linedit_completion', "#sec298").
